line_length: 120

trailing_whitespace:
  ignores_comments: false

disabled_rules:
  - todo
  - function_parameter_count
  - type_body_length
  - file_length
  - force_cast
  - identifier_name
  - cyclomatic_complexity
